name: fluent_validator
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/ErkinKurt/fluent_validator
repository: https://github.com/ErkinKurt/fluent_validator

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  very_good_analysis: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null